volumes:
  backend_src:
    name: backend_src
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./backend/src

  postgres_data:
    name: postgres_data
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./postgres_data

networks:
  ft_transcendence:
    name: ft_transcendence

services:
  postgres:
    container_name: postgres
    image: postgres
    env_file: .env
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - ft_transcendence

  backend:
    container_name: backend
    build: ./backend
    env_file: .env
    restart: always
    volumes:
      - backend_src:/usr/src/app
    ports:
      - 8000:8000
    depends_on:
      - postgres
    networks:
      - ft_transcendence
