# Generated by Django 5.0.1 on 2024-01-23 23:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pong', '0002_chat_message'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='chat',
        ),
        migrations.RemoveField(
            model_name='message',
            name='sender',
        ),
        migrations.DeleteModel(
            name='Chat',
        ),
        migrations.DeleteModel(
            name='Message',
        ),
    ]
