# Generated by Django 5.0.2 on 2024-02-26 20:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pong', '0007_alter_game_round'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='round',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='games', to='pong.round'),
        ),
    ]
