# Generated by Django 5.0.2 on 2024-02-26 20:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pong', '0008_alter_game_round'),
    ]

    operations = [
        migrations.AddField(
            model_name='score',
            name='game',
            field=models.OneToOneField(default=123, on_delete=django.db.models.deletion.CASCADE, related_name='score', to='pong.game'),
            preserve_default=False,
        ),
    ]
