# Generated by Django 5.0.2 on 2024-03-03 22:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='IsFriendsWith',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user1', to=settings.AUTH_USER_MODEL)),
                ('user2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user2', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='friends',
            field=models.ManyToManyField(through='user.IsFriendsWith', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='isfriendswith',
            constraint=models.UniqueConstraint(fields=('user1', 'user2'), name='user_isfriendswith_unique_relationships'),
        ),
        migrations.AddConstraint(
            model_name='isfriendswith',
            constraint=models.CheckConstraint(check=models.Q(('user1', models.F('user2')), _negated=True), name='user_isfriendswith_prevent_self_follow'),
        ),
    ]
