# Generated by Django 5.0.2 on 2024-03-04 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_remove_isfriendswith_user_isfriendswith_prevent_self_follow_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='isfriendswith',
            name='user_isfriendswith_prevent_self_add',
        ),
    ]
