# Generated by Django 5.0.2 on 2024-03-04 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_remove_isfriendswith_user_isfriendswith_prevent_self_add'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='isfriendswith',
            constraint=models.CheckConstraint(check=models.Q(('user1', models.F('user2')), _negated=True), name='user_isfriendswith_prevent_self_add'),
        ),
    ]
