# Generated by Django 5.0.2 on 2024-03-04 15:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_isfriendswith_user_isfriendswith_prevent_self_add'),
    ]

    operations = [
        migrations.CreateModel(
            name='IsBlockedBy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blocked', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocked_by', to=settings.AUTH_USER_MODEL)),
                ('blocker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocks', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='blocked_list',
            field=models.ManyToManyField(through='user.IsBlockedBy', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='isblockedby',
            constraint=models.UniqueConstraint(fields=('blocker', 'blocked'), name='user_isblockedby_unique_relationships'),
        ),
        migrations.AddConstraint(
            model_name='isblockedby',
            constraint=models.CheckConstraint(check=models.Q(('blocker', models.F('blocked')), _negated=True), name='user_isblockedby_prevent_self_block'),
        ),
    ]
